"""VAG ECU address map (used for auto-scan)."""

VAG_ECU_ADDRESSES: dict[int, str] = {
    0x01: "Engine Control Module (ECM)",
    0x02: "Automatic Transmission",
    0x03: "ABS Brakes",
    0x04: "Steering Angle Sensor",
    0x05: "Kessy / Access Control",
    0x06: "Seat Adjustment (Driver)",
    0x07: "Display Control Unit",
    0x08: "Auto HVAC",
    0x09: "Central Electrics",
    0x0A: "4WD / Haldex",
    0x0F: "Radio / Navigation",
    0x11: "Engine Electronics 2",
    0x13: "Auto Distance Regulation",
    0x14: "Wheel Damping Electronics",
    0x15: "Airbag",
    0x16: "Steering Wheel",
    0x17: "Instruments / Kombiinstrument",
    0x18: "AWD (Torsen)",
    0x19: "CAN Gateway",
    0x1A: "Drive Motor Electronics",
    0x22: "AWD 2",
    0x25: "Immobilizer",
    0x26: "Electronic Roof",
    0x29: "Left Light Control",
    0x2B: "Steering Column Electronics",
    0x2D: "Trailer Recognition",
    0x32: "Differential Lock",
    0x33: "Event Data Recorder",
    0x34: "Level Control System",
    0x36: "Seat Adjustment (Passenger)",
    0x37: "Navigation",
    0x39: "Right Light Control",
    0x3C: "Lane Change System",
    0x3D: "Special Function",
    0x42: "Door Electronics (Driver)",
    0x45: "Interior Monitoring",
    0x46: "Comfort System",
    0x47: "Sound System",
    0x4F: "Central Rear Module",
    0x52: "Door Electronics (Passenger)",
    0x53: "Parking Brake",
    0x55: "Headlight Range / Xenon",
    0x56: "Radio",
    0x57: "TV Tuner",
    0x5C: "Steering Control",
    0x5D: "Operation",
    0x5E: "Ctrl Head",
    0x61: "Battery Regulation",
    0x62: "Door Electronics (Rear Left)",
    0x65: "Tire Pressure Monitoring",
    0x69: "Trailer Function",
    0x72: "Door Electronics (Rear Right)",
    0x76: "Parking Aid",
    0x77: "Rain Sensor",
}
